-- DROP TABLE IF EXISTS user;
-- DROP TABLE IF EXISTS post;

-- CREATE TABLE user (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   username TEXT UNIQUE NOT NULL,
--   password TEXT NOT NULL
-- );

-- CREATE TABLE post (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   author_id INTEGER NOT NULL,
--   created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   title TEXT NOT NULL,
--   body TEXT NOT NULL,
--   FOREIGN KEY (author_id) REFERENCES user (id)
-- );

DROP TABLE IF EXISTS task;
-- DROP TABLE IF EXISTS post;

CREATE TABLE task (
  task_id INTEGER PRIMARY KEY AUTOINCREMENT,
  task_title TEXT NOT NULL,
  task_description TEXT,
  task_complete BOOLEAN NOT NULL
);
